# Plugins
plugins:
  - jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: [ '/automation/', 'README.md', 'LICENSE.txt', 'CNAME', 'vendor' ]

# Site Settings
title: "Madeira International Workshop in Machine Learning"
email: "secretariat@iknowd.org"
description: "This 5-day workshop is designed to show you the basic steps needed to start a Machine Learning project. On the first day, you will have an introduction to Python and see how to create neural networks in scikit-learn and TensorFlow."
url: "https://mml.iknowd.org"
permalink: "/blog/:title"

# Organizer Info
organizerName: "IKnowD"
organizerAlternateName: "Institute of Knowledge and Development"
organizerDescription: "The IKnowD, Institute of Knowledge and Development is a non-profit organisation with a strong will to help scientific and societal development, through spreading research results and supporting science."
organizerEmail: "secretariat@iknowd.org"
organizerLogo: "/img/seo/iknowd-logo.png"
organizerLink: "https://iknowd.org"

# Head
metaKeywords: "event, programming, developers, machine learning, tensorflow, mml"

# Navigation
navigationLinks:
  - { permalink: "/", text: "Home" }
  - { permalink: "/about-workshop/", text: "Workshop" }
  - { permalink: "/about-company-day/", text: "Company day" }
  - { permalink: "/schedule/", text: "Schedule" }
  - { permalink: "/speakers/", text: "Speakers" }
  - { permalink: "/team/", text: "Team" }
  - { permalink: "/sponsors/", text: "Sponsors" }

# Hero Block
heroImage: "hero.jpg"
heroTitle: "Madeira International Workshop in Machine Learning"
eventDate: "Madeira Tecnopolo, 18–22 July, 2022"
typeoutTextValues: ''
typeoutFallback: "Season"
heroButtons:
  - { permalink: "/about-company-day", text: "COMPANY DAY",type: "primary" }
  - { permalink: "/#tickets", text: "REGISTRATION", type: "success" }

# About workshop Block
aboutTitle: "About the Event"
aboutBlock:
  - { title: "Workshop", image: "workshop.jpg", text: "This workshop is designed to show the basic steps needed to start Machine Learning with Python." }
  - { title: "Talks", image: "talks.jpg", text: "We will have fascinating talks about AI given by a top researcher and a developer advocate at Google." }
  - { title: "Company Exhibition", image: "companies.jpg", text: "We will have a company exhibition, where you can get in touch with current technologies, make new contacts and eventually apply for job offers." }

# About workshop Block
aboutCompany: "Company day"

# Mission Block
missionTitle: "Mission"
missionBlock:
  - { title: "Vision", text: "This workshop shows the basic steps needed to start Machine Learning with Python. It also serves for sharing the knowledge with a beginner by showing the steps and tools related to the field. The planned sessions include theoretical lectures and practical sessions given by researchers with experience in Machine Learning applications. On the 4th day, we will have what we named <i>Company Day</i>, an entire day dedicated to companies (open to public, ticket free of charge). During the day, companies will have the opportunity to share their work, products, services and eventually do in-local job interviews." }
  - { title: "Prerequisites for the workshop", text: "– Personal laptop. <br/> – Basic knowledge of programming. <br/> – Hands on experience with basic Python.<br/> – Machine Learning knowledge is desirable, though not mandatory." }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
  - { count: "400", specialCharacter: "+", info: "attendees", detail: "from everywhere" }
  - { count: "15", specialCharacter: "+", info: "hours", detail: "of pure AI topics" }
  - { count: "4", specialCharacter: "", info: "speakers", detail: "experts in different topics" }

# Latest News Block
latestNewsTitle: "Latest news"

# Rockstar Speakers Block
rockstarSpeakersImage: "featured-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Featured Speakers"
rockstarSpeakersButtonText: "See all speakers"

# Venue Block
venueBlockTitle: "Venue"
venueBigImage: "tecnopolo_0.jpg"
venueSmallImage1: "tecnopolo_1.jpg"
venueSmallImage2: "tecnopolo_2.jpg"
venueTitle: "Madeira Tecnopolo (<a style='color: white; text-decoration: underline;' href='https://goo.gl/maps/YwNSVU1FbJT3cSBL6' target='_blank'>link</a>)"
venueFeatures: [ "– Accessible rooms", "– Bar and restaurant available", "– Located near the University of Madeira", "– Parking slots available" ]

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Partners"

# Copyright block
copyrightTitle: "Image copyrights"

# Tickets Block
ticketsTitle: "Registration Fees"
ticketsInfo: "Both types of registration will provide access to all the files and presentations used during the workshop."
ticketsOffers:
  - name: "Early Bird—Students"
    price: "25"
    priceCurrency: "EUR"
    ticketsNumber: "20"
    buyButtonLink: "https://docs.google.com/forms/d/e/1FAIpQLSf0HJrjQrai8eUJ3UOQjLMtYvwOWRMZIep6hgZbi3XK9-VNvg/viewform?usp=pp_url&entry.55643516=Early+Bird%E2%80%94Students+(25+euros)"
    buyButtonText: "Buy Now"
    additionalInfo: "Requires a sending a valid student ID after purchasing the ticket."
    validFrom: "2022-06-27T10:00"
    validThrough: "2022-07-03T23:59"
    disabled: false

  - name: "Early Bird—Regular"
    price: "50"
    priceCurrency: "EUR"
    ticketsNumber: "50"
    buyButtonLink: "https://docs.google.com/forms/d/e/1FAIpQLSfBt0hBmw6rHQhVDXbKrhoat9h-aw8DB2-FA46-4mPcJVhJlQ/viewform?usp=pp_url&entry.55643516=Early+Bird%E2%80%94Regular+(50+euros)"
    buyButtonText: "Buy Now"
    validFrom: "2022-06-27T10:00"
    validThrough: "2022-07-03T23:59"
    disabled: false

  - name: "Student"
    price: "35"
    priceCurrency: "EUR"
    ticketsNumber: "20"
    featured: true
    buyButtonLink: "#"
    buyButtonText: "Buy Now"
    additionalInfo: "Requires a sending a valid student ID after purchasing the ticket."
    validFrom: "2022-07-04T00:00"
    validThrough: "2022-07-15T23:59"
    disabled: false

  - name: "Regular"
    price: "70"
    priceCurrency: "EUR"
    ticketsNumber: "40"
    featured: true
    buyButtonLink: "#"
    buyButtonText: "Buy Now"
    validFrom: "2022-07-04T00:00"
    validThrough: "2022-07-15T23:59"
    disabled: false

footerBlocks:
  - title: "Links"
    links:
      - { link: "https://iknowd.org", text: "IKnowD.org" }
  - title: "Contacts"
    links:
      - { link: "mailto:secretariat@iknowd.org", text: "secretariat@iknowd.org" }
  - title: "Past events"
    links:
      - { link: "https://iknowd.org/tccf_21/mml_21", text: "2021" }
  - title: "Other information"
    links:
      - { permalink: "/cod/", text: "Code of Conduct" }
      - { permalink: "/copyrights/", text: "Image copyrights" }

# Speakers List Block
showSessions: true

# About the Event Block
aboutEvent: If you need more information please feel free to contact using this email address <a href='mailto:secretariat@iknowd.org'>secretariat@iknowd.org</a>.

# Agenda Block
aboutAgenda: <b>Note:</b> This will be a 5-day workshop starting from July 18. The following is the tentative agenda for the workshop.
